### ISSUE TITLE
Add unicode support for CSV files

### ISSUE THREAD

**Issue by andrej-sajenko** [thm-mni-ii/tals#7]
The Moodle plugin does not support the export of CSV values with umlauts.

**Comment by andrej-sajenko** [comment]
Exel does not recognise that the file is encoded as utf-8.

First google search results on this issue suggest to export the file with a BOM.
See: https://stackoverflow.com/questions/6002256/is-it-possible-to-force-excel-recognize-utf-8-csv-files-automatically

**Comment by lshw42** [comment]
This bug is closed due to commit b1c3b53
